### ISSUE TITLE
Win32Exception "Invalid device context (DC) handle" in Frame.Overwrite

### ISSUE THREAD

**Issue by jnm2** [Techsola/InstantReplay#12]
```
   at Techsola.InstantReplay.InstantReplayCamera.Frame.Overwrite(DeviceContextSafeHandle bitmapDC, DeviceContextSafeHandle windowDC, Int32 windowClientLeft, Int32 windowClientTop, Int32 windowClientWidth, Int32 windowClientHeight, UInt32 windowDpi, UInt32 zOrder, Boolean& needsGdiFlush)
   at Techsola.InstantReplay.InstantReplayCamera.AddFrames(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by jnm2** [comment]
It's line 79:
https://github.com/Techsola/InstantReplay/blob/2025d7823ce1f7266d1a77c6a8a3665984fbc273/src/Techsola.InstantReplay/Frame.cs#L76-L79

And when stopped in the debugger, `User32.IsWindowVisible(windowDC.HWnd.Value)` is `true`, but `Gdi32.CreateCompatibleDC(windowDC.DangerousGetHandle()).IsInvalid` is `true`.

And the window handle is for the maximized main window which is not closing.

Perhaps it's normal for a window's device context to be replaced over time.

**Comment by jnm2** [comment]
Another repro shows that Techsola.InstantReplay is not the one releasing/deleting the device context:
![image](https://user-images.githubusercontent.com/8040367/106025890-33c7ea80-6097-11eb-86ee-4355cdefee4d.png)

![image](https://user-images.githubusercontent.com/8040367/106025925-3d515280-6097-11eb-9be1-ba434ca78c2d.png)

So the DC replacement is something it will just have to detect and respond to.
